### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by zappybiby** [lachjames/MLStone#1]
Hello! I am new to Github, so hopefully this is the right way to go about this...

I wanted to know if there is a way currently to scale down the predicted deck, since right now it goes off the screen even when it is maximized to 1920x1080.

I would love to donate if you plan on continuing to update this! I think there is huge potential here. I am sure you have already looked at this, but Elie Burszstein has worked on something similar: https://cdn.elie.net/publications/i-am-a-legend-hacking-hearthstone-using-statistical-learning-methods.pdf

**Comment by lachjames** [comment]
Hi :)

Thanks for your feedback! In the next build I'm going to split the list of cards into two lists adjacent to one another, which should solve your issue. In a future build I'll add a configuration menu which will allow you to modify settings such as scaling.

I'm certainly planning to keep updating this, as I've wanted to work on it for a while and it's a lot of fun! Regarding donations, that's really not necessary; the fact that you're willing to donate at all is enough to inspire me to keep working on it even harder :)

Thanks,

Lachlan
